name: Open/Edit/Sync Pull Request
on:
  pull_request:
    types: ["opened", "synchronize"]
    branches: ["staging"]

jobs:
  jslint:
    name: ESlint with comments in /src
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ESlint reviewdog action
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: "src/"
          filter_mode: nofilter
          fail_on_error: true

  jslintassets:
    name: ESlint with comments in /assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ESlint reviewdog action
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: "assets/"
          fail_on_error: true

  stylelint:
    name: Stylelint with comments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stylelint reviewdog action
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review
          stylelint_input: "**/*.scss"
          filter_mode: nofilter
          fail_on_error: true

  preview:
    name: Deploy preview theme
    runs-on: ubuntu-latest
    needs:
      - jslint
      - stylelint
      - jslintassets

    if: needs.jslint.result == 'success' && needs.stylelint.result == 'success' && needs.jslintassets.result == 'success'

    env:
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ github.event.pusher.email }}"

      - name: Push to preview
        run: git push origin HEAD:dev --force